In [1]:
# 1st Numpy

# install numpy by
pip install numpy

TYPES:-
1.single dimensional array 
2.two  dimensional array [rows & columns]
3.multi dimensional array [mariex]

In [4]:
#single dimensional array
import numpy as np
d1_arr=np.array([1,2,3,4,5,6])
print(d1_arr)

[1 2 3 4 5 6]


In [5]:
# two dimensional array
import numpy as np
d1_arr=np.array([[1,2,3],
                  [4,5,6]])
print(d1_arr)

[[1 2 3]
 [4 5 6]]


In [6]:
# multi dimensional array  *matriex

import numpy as np
matriex=np.array([[1,2,3],
                  [4,5,6]])
print(matriex)

[[1 2 3]
 [4 5 6]]
